apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-logs
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.158.2"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: observability
  values:
    mode: daemonset

    image:
      repository: otel/opentelemetry-collector-contrib

    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: false
      kubernetesAttributes:
        enabled: true

    config:
      receivers:
        filelog:
          include:
            - /var/log/pods/*/*/*.log
          start_at: end
          include_file_path: true
          include_file_name: false
          operators:
            - type: container

      processors:
        k8sattributes:
          auth_type: serviceAccount
          extract:
            metadata:
              - k8s.namespace.name
              - k8s.pod.name
              - k8s.container.name
              - k8s.node.name
        batch: {}

      exporters:
        otlphttp/loki:
          endpoint: http://loki-gateway.observability.svc.cluster.local/otlp

      service:
        pipelines:
          logs:
            receivers: [filelog]
            processors: [k8sattributes, batch]
            exporters: [otlphttp/loki]