apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab-runner
  namespace: runners
spec:
  replicas: 1
  template:
    spec:
      repository: k8sVoodoo/infra-gitops
      labels:
        - docker-desktop
        - homelab
        - flux