apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: runners
type: Opaque
stringData:
  github_token: ghp_REPLACE_ME

#######################################################
# kubectl create secret generic controller-manager \
#  -n runners \
# --from-literal=github_token=YOUR_GITHUB_PAT