name: Test ARC Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - run: echo "ARC runner is working"
      - run: hostname
      - run: uname -a
      - run: whoami
      - run: pwd